
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 15 14:36:05 CEST 2016
//----------------------------------------------------

package gralog.modallogic.parser;

import java_cup.runtime.*;
import gralog.modallogic.formula.*;
import java.io.ByteArrayInputStream;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Jul 15 14:36:05 CEST 2016
  */
public class ModalLogicParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ModalLogicParser() {super();}

  /** Constructor which sets the default scanner. */
  public ModalLogicParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ModalLogicParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\017\000\002\002\003\000\002\002\004\000\002\003" +
    "\005\000\002\003\003\000\002\004\005\000\002\004\003" +
    "\000\002\005\003\000\002\005\005\000\002\005\003\000" +
    "\002\005\003\000\002\005\004\000\002\005\005\000\002" +
    "\005\006\000\002\005\005\000\002\005\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\036\000\020\004\015\006\004\010\006\011\007\014" +
    "\014\015\016\017\010\001\002\000\006\007\035\017\034" +
    "\001\002\000\010\002\ufffe\013\032\016\ufffe\001\002\000" +
    "\012\002\ufff9\012\ufff9\013\ufff9\016\ufff9\001\002\000\012" +
    "\002\ufff8\012\ufff8\013\ufff8\016\ufff8\001\002\000\012\002" +
    "\ufffb\012\ufffb\013\ufffb\016\ufffb\001\002\000\006\002\001" +
    "\016\001\001\002\000\004\002\031\001\002\000\012\002" +
    "\ufffc\012\027\013\ufffc\016\ufffc\001\002\000\020\004\015" +
    "\006\004\010\006\011\007\014\014\015\016\017\010\001" +
    "\002\000\006\005\021\017\022\001\002\000\020\004\015" +
    "\006\004\010\006\011\007\014\014\015\016\017\010\001" +
    "\002\000\004\016\020\001\002\000\012\002\ufffa\012\ufffa" +
    "\013\ufffa\016\ufffa\001\002\000\020\004\015\006\004\010" +
    "\006\011\007\014\014\015\016\017\010\001\002\000\004" +
    "\005\023\001\002\000\020\004\015\006\004\010\006\011" +
    "\007\014\014\015\016\017\010\001\002\000\012\002\ufff5" +
    "\012\ufff5\013\ufff5\016\ufff5\001\002\000\012\002\ufff6\012" +
    "\ufff6\013\ufff6\016\ufff6\001\002\000\012\002\ufff7\012\ufff7" +
    "\013\ufff7\016\ufff7\001\002\000\020\004\015\006\004\010" +
    "\006\011\007\014\014\015\016\017\010\001\002\000\010" +
    "\002\ufffd\013\ufffd\016\ufffd\001\002\000\004\002\000\001" +
    "\002\000\020\004\015\006\004\010\006\011\007\014\014" +
    "\015\016\017\010\001\002\000\006\002\uffff\016\uffff\001" +
    "\002\000\004\007\037\001\002\000\020\004\015\006\004" +
    "\010\006\011\007\014\014\015\016\017\010\001\002\000" +
    "\012\002\ufff4\012\ufff4\013\ufff4\016\ufff4\001\002\000\020" +
    "\004\015\006\004\010\006\011\007\014\014\015\016\017" +
    "\010\001\002\000\012\002\ufff3\012\ufff3\013\ufff3\016\ufff3" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\036\000\012\002\011\003\010\004\004\005\012\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\025\001\001" +
    "\000\002\001\001\000\012\002\016\003\010\004\004\005" +
    "\012\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\024\001\001\000\002\001\001\000\004\005\023\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\004\027\005\012\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\003\032\004\004\005\012\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\035\001" +
    "\001\000\002\001\001\000\004\005\037\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ModalLogicParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ModalLogicParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ModalLogicParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    String errorMsg = null;

    public Boolean hasError()
    {
        return errorMsg == null;
    }
    
    public String getErrorMsg()
    {
        if(errorMsg == null)
            return "no error";
        else
            return errorMsg;
    }
    
    public void syntax_error(Symbol cur_token)
    {
        if(errorMsg == null)
            errorMsg = "Syntax Error: " + cur_token.toString();
    }

    public void report_fatal_error(String message, Object info) throws Exception
    {
        throw new Exception("Fatal parsing error: " + message + "\n" + info.toString());
    }

    public ModalLogicFormula parseString(String str) throws Exception
    {
        String charset = "UTF8";
        byte[] bytes = str.getBytes(charset);
        ByteArrayInputStream stringstream = new ByteArrayInputStream(bytes);
                
        DefaultSymbolFactory symbolfactory = new DefaultSymbolFactory();
        ModalLogicScanner scanner = new ModalLogicScanner(stringstream, symbolfactory);
        this.setScanner(scanner);
        
        Symbol parserresult = this.parse();
        return (ModalLogicFormula) parserresult.value;
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ModalLogicParser$actions {
  private final ModalLogicParser parser;

  /** Constructor */
  CUP$ModalLogicParser$actions(ModalLogicParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ModalLogicParser$do_action(
    int                        CUP$ModalLogicParser$act_num,
    java_cup.runtime.lr_parser CUP$ModalLogicParser$parser,
    java.util.Stack            CUP$ModalLogicParser$stack,
    int                        CUP$ModalLogicParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ModalLogicParser$result;

      /* select the action based on the action number */
      switch (CUP$ModalLogicParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // atomicformula ::= BRACKETLEFT STRING BRACKETRIGHT atomicformula 
            {
              ModalLogicFormula RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = new ModalLogicBox(s, f); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-3)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // atomicformula ::= BRACKETLEFT BRACKETRIGHT atomicformula 
            {
              ModalLogicFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = new ModalLogicBox(f); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // atomicformula ::= LT STRING GT atomicformula 
            {
              ModalLogicFormula RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = new ModalLogicDiamond(s, f); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-3)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // atomicformula ::= LT GT atomicformula 
            {
              ModalLogicFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = new ModalLogicDiamond(f); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // atomicformula ::= NEG atomicformula 
            {
              ModalLogicFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = new ModalLogicNot(f); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-1)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // atomicformula ::= TOP 
            {
              ModalLogicFormula RESULT =null;
		 RESULT = new ModalLogicTop(); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // atomicformula ::= BOT 
            {
              ModalLogicFormula RESULT =null;
		 RESULT = new ModalLogicBottom(); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // atomicformula ::= PARENTHESISLEFT formula PARENTHESISRIGHT 
            {
              ModalLogicFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-1)).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-1)).value;
		 RESULT = f; 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // atomicformula ::= STRING 
            {
              ModalLogicFormula RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = new ModalLogicProposition(s); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // wedgeformula ::= atomicformula 
            {
              ModalLogicFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = f; 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("wedgeformula",2, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // wedgeformula ::= atomicformula WEDGE wedgeformula 
            {
              ModalLogicFormula RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).right;
		ModalLogicFormula left = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula right = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = new ModalLogicAnd(left, right); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("wedgeformula",2, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // veeformula ::= wedgeformula 
            {
              ModalLogicFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = f; 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("veeformula",1, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // veeformula ::= wedgeformula VEE veeformula 
            {
              ModalLogicFormula RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).right;
		ModalLogicFormula left = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula right = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = new ModalLogicOr(left, right); 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("veeformula",1, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-2)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= formula EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-1)).right;
		ModalLogicFormula start_val = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-1)).value;
		RESULT = start_val;
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.elementAt(CUP$ModalLogicParser$top-1)), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ModalLogicParser$parser.done_parsing();
          return CUP$ModalLogicParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // formula ::= veeformula 
            {
              ModalLogicFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()).right;
		ModalLogicFormula f = (ModalLogicFormula)((java_cup.runtime.Symbol) CUP$ModalLogicParser$stack.peek()).value;
		 RESULT = f; 
              CUP$ModalLogicParser$result = parser.getSymbolFactory().newSymbol("formula",0, ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ModalLogicParser$stack.peek()), RESULT);
            }
          return CUP$ModalLogicParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

