
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 19 13:06:55 CET 2015
//----------------------------------------------------

package gralog.modallogic.parser;

/** CUP generated class containing symbol constants. */
public class ModalLogicScannerToken {
  /* terminals */
  public static final int BRACKETLEFT = 4;
  public static final int BOT = 6;
  public static final int TOP = 7;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int WEDGE = 8;
  public static final int PARENTHESISRIGHT = 12;
  public static final int GT = 3;
  public static final int VEE = 9;
  public static final int error = 1;
  public static final int NEG = 10;
  public static final int BRACKETRIGHT = 5;
  public static final int LT = 2;
  public static final int PARENTHESISLEFT = 11;
}

