
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 07 16:17:57 CET 2016
//----------------------------------------------------

package gralog.modallogic.parser;

/** CUP generated class containing symbol constants. */
public class ModalLogicScannerToken {
  /* terminals */
  public static final int BOX = 7;
  public static final int BRACKETLEFT = 4;
  public static final int BOT = 8;
  public static final int TOP = 9;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int WEDGE = 10;
  public static final int PARENTHESISRIGHT = 14;
  public static final int GT = 3;
  public static final int VEE = 11;
  public static final int DIAMOND = 6;
  public static final int error = 1;
  public static final int NEG = 12;
  public static final int BRACKETRIGHT = 5;
  public static final int LT = 2;
  public static final int PARENTHESISLEFT = 13;
}

