package gralog.dialog;

public enum DialogState { ASK_WHAT_TO_SELECT, ASK_WHAT_TO_DESELECT, WAIT_FOR_WHAT_TO_SELECT, WAIT_FOR_WHAT_TO_DESELECT,
    ASK_WHAT_TO_FILTER, WAIT_FOR_WHAT_TO_FILTER, FILTER_ALL_ASK_FILTER_CONDITION,
      FILTER_ALL_VERTICES_ASK_FILTER_CONDITION, FILTER_ALL_EDGES_ASK_FILTER_CONDITION,
    DONE
}
