
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 19 16:47:48 CET 2015
//----------------------------------------------------

package gralog.automaton.regularexpression.parser;

/** CUP generated class containing symbol constants. */
public class RegularExpressionScannerToken {
  /* terminals */
  public static final int STRING = 6;
  public static final int PARENTHESISRIGHT = 3;
  public static final int PARENTHESISLEFT = 2;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int ALTERNATION = 5;
  public static final int KLEENESTAR = 4;
}

