
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 15 14:36:04 CEST 2016
//----------------------------------------------------

package gralog.firstorderlogic.logic.firstorder.parser;

import java_cup.runtime.*;
import gralog.firstorderlogic.logic.firstorder.formula.*;
import java.io.ByteArrayInputStream;
import java.util.Vector;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Jul 15 14:36:04 CEST 2016
  */
public class FirstOrderParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public FirstOrderParser() {super();}

  /** Constructor which sets the default scanner. */
  public FirstOrderParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public FirstOrderParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\015\000\002\002\003\000\002\002\004\000\002\003" +
    "\005\000\002\003\003\000\002\004\005\000\002\004\003" +
    "\000\002\005\004\000\002\005\005\000\002\005\006\000" +
    "\002\005\006\000\002\005\006\000\002\006\003\000\002" +
    "\006\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\036\000\014\004\005\006\014\011\010\012\006\015" +
    "\007\001\002\000\010\002\ufffe\005\ufffe\010\037\001\002" +
    "\000\014\004\005\006\014\011\010\012\006\015\007\001" +
    "\002\000\004\015\032\001\002\000\004\004\024\001\002" +
    "\000\004\015\021\001\002\000\006\002\001\005\001\001" +
    "\002\000\004\002\020\001\002\000\012\002\ufffc\005\ufffc" +
    "\007\016\010\ufffc\001\002\000\014\004\005\006\014\011" +
    "\010\012\006\015\007\001\002\000\012\002\ufffb\005\ufffb" +
    "\007\ufffb\010\ufffb\001\002\000\014\004\005\006\014\011" +
    "\010\012\006\015\007\001\002\000\010\002\ufffd\005\ufffd" +
    "\010\ufffd\001\002\000\004\002\000\001\002\000\004\014" +
    "\022\001\002\000\014\004\005\006\014\011\010\012\006" +
    "\015\007\001\002\000\012\002\ufff8\005\ufff8\007\ufff8\010" +
    "\ufff8\001\002\000\004\015\025\001\002\000\006\005\ufff6" +
    "\013\ufff6\001\002\000\006\005\030\013\027\001\002\000" +
    "\004\015\031\001\002\000\012\002\ufff9\005\ufff9\007\ufff9" +
    "\010\ufff9\001\002\000\006\005\ufff5\013\ufff5\001\002\000" +
    "\004\014\033\001\002\000\014\004\005\006\014\011\010" +
    "\012\006\015\007\001\002\000\012\002\ufff7\005\ufff7\007" +
    "\ufff7\010\ufff7\001\002\000\004\005\036\001\002\000\012" +
    "\002\ufffa\005\ufffa\007\ufffa\010\ufffa\001\002\000\014\004" +
    "\005\006\014\011\010\012\006\015\007\001\002\000\006" +
    "\002\uffff\005\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\036\000\012\002\011\003\010\004\003\005\012\001" +
    "\001\000\002\001\001\000\012\002\034\003\010\004\003" +
    "\005\012\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\014\001\001\000\002\001\001\000" +
    "\006\004\016\005\012\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\022\001\001\000" +
    "\002\001\001\000\004\006\025\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\033\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\003\037\004\003\005\012\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$FirstOrderParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$FirstOrderParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$FirstOrderParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    String errorMsg = null;

    public Boolean hasError()
    {
        return errorMsg == null;
    }
    
    public String getErrorMsg()
    {
        if(errorMsg == null)
            return "no error";
        else
            return errorMsg;
    }
    
    public void syntax_error(Symbol cur_token)
    {
        if(errorMsg == null)
            errorMsg = "Syntax Error: " + cur_token.toString();
    }

    public void report_fatal_error(String message, Object info) throws Exception
    {
        throw new Exception("Fatal parsing error: " + message + "\n" + info.toString());
    }

    public FirstOrderFormula parseString(String str) throws Exception
    {
        String charset = "UTF8";
        byte[] bytes = str.getBytes(charset);
        ByteArrayInputStream stringstream = new ByteArrayInputStream(bytes);
                
        DefaultSymbolFactory symbolfactory = new DefaultSymbolFactory();
        FirstOrderScanner scanner = new FirstOrderScanner(stringstream, symbolfactory);
        this.setScanner(scanner);
        
        Symbol parserresult = this.parse();
        return (FirstOrderFormula) parserresult.value;
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$FirstOrderParser$actions {
  private final FirstOrderParser parser;

  /** Constructor */
  CUP$FirstOrderParser$actions(FirstOrderParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$FirstOrderParser$do_action(
    int                        CUP$FirstOrderParser$act_num,
    java_cup.runtime.lr_parser CUP$FirstOrderParser$parser,
    java.util.Stack            CUP$FirstOrderParser$stack,
    int                        CUP$FirstOrderParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$FirstOrderParser$result;

      /* select the action based on the action number */
      switch (CUP$FirstOrderParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // parameters ::= parameters COMMA STRING 
            {
              Vector<String> RESULT =null;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).right;
		Vector<String> params = (Vector<String>)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = params; RESULT.add(s); 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("parameters",4, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // parameters ::= STRING 
            {
              Vector<String> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = new Vector<String>(); RESULT.add(s); 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("parameters",4, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // atomicformula ::= FORALL STRING DOT atomicformula 
            {
              FirstOrderFormula RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).left;
		int varright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).right;
		String var = (String)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		FirstOrderFormula f = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = new FirstOrderForall(var, f); 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-3)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // atomicformula ::= EXISTS STRING DOT atomicformula 
            {
              FirstOrderFormula RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).left;
		int varright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).right;
		String var = (String)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		FirstOrderFormula f = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = new FirstOrderExists(var, f); 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-3)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // atomicformula ::= STRING OPEN parameters CLOSE 
            {
              FirstOrderFormula RESULT =null;
		int relleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-3)).left;
		int relright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-3)).right;
		String rel = (String)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-3)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).right;
		Vector<String> params = (Vector<String>)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).value;
		 RESULT = new FirstOrderRelation(rel, params); 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-3)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // atomicformula ::= OPEN formula CLOSE 
            {
              FirstOrderFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).right;
		FirstOrderFormula f = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).value;
		 RESULT = f; 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // atomicformula ::= NEG atomicformula 
            {
              FirstOrderFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		FirstOrderFormula f = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = new FirstOrderNot(f); 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("atomicformula",3, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // wedgeformula ::= atomicformula 
            {
              FirstOrderFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		FirstOrderFormula f = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = f; 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("wedgeformula",2, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // wedgeformula ::= atomicformula AND wedgeformula 
            {
              FirstOrderFormula RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).right;
		FirstOrderFormula left = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		FirstOrderFormula right = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = new FirstOrderAnd(left, right); 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("wedgeformula",2, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // veeformula ::= wedgeformula 
            {
              FirstOrderFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		FirstOrderFormula f = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = f; 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("veeformula",1, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // veeformula ::= wedgeformula OR veeformula 
            {
              FirstOrderFormula RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).right;
		FirstOrderFormula left = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		FirstOrderFormula right = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = new FirstOrderOr(left, right); 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("veeformula",1, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-2)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= formula EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).right;
		FirstOrderFormula start_val = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)).value;
		RESULT = start_val;
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.elementAt(CUP$FirstOrderParser$top-1)), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$FirstOrderParser$parser.done_parsing();
          return CUP$FirstOrderParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // formula ::= veeformula 
            {
              FirstOrderFormula RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()).right;
		FirstOrderFormula f = (FirstOrderFormula)((java_cup.runtime.Symbol) CUP$FirstOrderParser$stack.peek()).value;
		 RESULT = f; 
              CUP$FirstOrderParser$result = parser.getSymbolFactory().newSymbol("formula",0, ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$FirstOrderParser$stack.peek()), RESULT);
            }
          return CUP$FirstOrderParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

