
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 08 12:43:13 CEST 2016
//----------------------------------------------------

package gralog.firstorderlogic.logic.firstorder.parser;

/** CUP generated class containing symbol constants. */
public class FirstOrderScannerToken {
  /* terminals */
  public static final int AND = 5;
  public static final int OPEN = 2;
  public static final int FORALL = 8;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int EXISTS = 7;
  public static final int DOT = 10;
  public static final int CLOSE = 3;
  public static final int COMMA = 9;
  public static final int error = 1;
  public static final int NEG = 4;
  public static final int OR = 6;
}

