
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 18 14:53:47 CEST 2016
//----------------------------------------------------

package gralog.npcompleteness.propositionallogic.parser;

/** CUP generated class containing symbol constants. */
public class PropositionalLogicScannerToken {
  /* terminals */
  public static final int STRING = 7;
  public static final int AND = 5;
  public static final int error = 1;
  public static final int NEG = 4;
  public static final int OPEN = 2;
  public static final int OR = 6;
  public static final int CLOSE = 3;
  public static final int EOF = 0;
}

