
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 15 14:36:06 CEST 2016
//----------------------------------------------------

package gralog.modalmucalculus.parser;

/** CUP generated class containing symbol constants. */
public class ModalMuCalculusScannerToken {
  /* terminals */
  public static final int BRACKETLEFT = 4;
  public static final int NU = 8;
  public static final int BOT = 9;
  public static final int TOP = 10;
  public static final int STRING = 16;
  public static final int EOF = 0;
  public static final int WEDGE = 11;
  public static final int MU = 7;
  public static final int PARENTHESISRIGHT = 15;
  public static final int DOT = 6;
  public static final int GT = 3;
  public static final int VEE = 12;
  public static final int error = 1;
  public static final int NEG = 13;
  public static final int BRACKETRIGHT = 5;
  public static final int LT = 2;
  public static final int PARENTHESISLEFT = 14;
}

