
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 14 16:41:40 CEST 2016
//----------------------------------------------------

package gralog.computationtreelogic.parser;

/** CUP generated class containing symbol constants. */
public class ComputationTreeLogicScannerToken {
  /* terminals */
  public static final int ALWAYS = 2;
  public static final int BOT = 8;
  public static final int TOP = 9;
  public static final int GLOBALLY = 5;
  public static final int NEXT = 4;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int WEDGE = 10;
  public static final int EXISTS = 3;
  public static final int PARENTHESISRIGHT = 14;
  public static final int VEE = 11;
  public static final int error = 1;
  public static final int FINALLY = 6;
  public static final int UNTIL = 7;
  public static final int NEG = 12;
  public static final int PARENTHESISLEFT = 13;
}

