
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gralog.modalmucalculus.parser;

/** CUP generated class containing symbol constants. */
public class ModalMuCalculusScannerToken {
  /* terminals */
  public static final int AND = 13;
  public static final int LT = 2;
  public static final int NEG = 15;
  public static final int OR = 14;
  public static final int PARENTHESISRIGHT = 17;
  public static final int GT = 3;
  public static final int MU = 7;
  public static final int BRACKETRIGHT = 5;
  public static final int STRING = 18;
  public static final int BOX = 10;
  public static final int EOF = 0;
  public static final int BOT = 11;
  public static final int TOP = 12;
  public static final int BRACKETLEFT = 4;
  public static final int error = 1;
  public static final int DOT = 6;
  public static final int NU = 8;
  public static final int PARENTHESISLEFT = 16;
  public static final int DIAMOND = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LT",
  "GT",
  "BRACKETLEFT",
  "BRACKETRIGHT",
  "DOT",
  "MU",
  "NU",
  "DIAMOND",
  "BOX",
  "BOT",
  "TOP",
  "AND",
  "OR",
  "NEG",
  "PARENTHESISLEFT",
  "PARENTHESISRIGHT",
  "STRING"
  };
}

